#############################################################################
# Makefile for building: libhildonplugin.so
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sat Mar 2 16:10:33 2013
# Project:  components.pro
# Template: lib
# Command: /usr/bin/qmake PREFIX=/usr -o Makefile components.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GL_NO_SCISSOR_TEST -DQT_DEFAULT_TEXTURE_GLYPH_CACHE_WIDTH=1024 -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O3 -mfpu=neon -ffast-math -flto=4 -fgraphite -ftree-vectorize -mthumb -fno-strict-volatile-bitfields -Wno-cast-align -Wno-psabi -fno-inline-functions -fno-unswitch-loops -fno-predictive-commoning -fno-gcse-after-reload -fno-ipa-cp-clone -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -mfpu=neon -ffast-math -flto=4 -fgraphite -ftree-vectorize -mthumb -fno-strict-volatile-bitfields -Wno-cast-align -Wno-psabi -fno-inline-functions -fno-unswitch-loops -fno-predictive-commoning -fno-gcse-after-reload -fno-ipa-cp-clone -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/linux-g++-maemo5 -I. -I/targets/FREMANTLE_ARMEL_GCC472/usr/include/QtCore -I/targets/FREMANTLE_ARMEL_GCC472/usr/include/QtNetwork -I/targets/FREMANTLE_ARMEL_GCC472/usr/include/QtGui -I/targets/FREMANTLE_ARMEL_GCC472/usr/include/QtDBus -I/targets/FREMANTLE_ARMEL_GCC472/usr/include/QtDeclarative -I/targets/FREMANTLE_ARMEL_GCC472/usr/include -I/targets/FREMANTLE_ARMEL_GCC472/usr/include/QtSystemInfo -I/targets/FREMANTLE_ARMEL_GCC472/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath-link,/usr/lib -Wl,-O1 -Wl,--hash-style=gnu -O3 -ffast-math -fgraphite -ftree-vectorize -fno-inline-functions -fno-unswitch-loops -fno-predictive-commoning -fno-gcse-after-reload -fno-ipa-cp-clone -Wl,-rpath,/usr/lib -Wl,-rpath,/usr/lib -shared
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/lib -lQtSystemInfo -lQtDeclarative -lQtScript -lQtSvg -L/usr/X11R6/lib -lQtSql -lQtXmlPatterns -lQtGui -lQtNetwork -lQtDBus -lQtXml -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/fileinfothread.cpp \
		src/qdeclarativefolderlistmodel.cpp \
		src/filesystemmodel.cpp \
		src/hildonscreenplugin.cpp \
		src/hildonsystemplugin.cpp \
		src/maskeditem.cpp \
		src/maskeffect.cpp \
		src/effects.cpp \
		src/hildonwindowplugin.cpp \
		src/qdeclarativeprocess.cpp \
		src/qdeclarativesettings.cpp \
		src/hildonthemeplugin.cpp \
		src/hildonimageprovider.cpp moc_fileinfothread_p.cpp \
		moc_qdeclarativefolderlistmodel.cpp \
		moc_filesystemmodel.cpp \
		moc_hildonscreenplugin.cpp \
		moc_hildonsystemplugin.cpp \
		moc_hildonthemeplugin.cpp \
		moc_maskeditem.cpp \
		moc_maskeffect.cpp \
		moc_effects.cpp \
		moc_hildonenums.cpp \
		moc_hildonwindowplugin.cpp \
		moc_qdeclarativeprocess.cpp \
		moc_plugin.cpp \
		moc_qdeclarativesettings.cpp
OBJECTS       = fileinfothread.o \
		qdeclarativefolderlistmodel.o \
		filesystemmodel.o \
		hildonscreenplugin.o \
		hildonsystemplugin.o \
		maskeditem.o \
		maskeffect.o \
		effects.o \
		hildonwindowplugin.o \
		qdeclarativeprocess.o \
		qdeclarativesettings.o \
		hildonthemeplugin.o \
		hildonimageprovider.o \
		moc_fileinfothread_p.o \
		moc_qdeclarativefolderlistmodel.o \
		moc_filesystemmodel.o \
		moc_hildonscreenplugin.o \
		moc_hildonsystemplugin.o \
		moc_hildonthemeplugin.o \
		moc_maskeditem.o \
		moc_maskeffect.o \
		moc_effects.o \
		moc_hildonenums.o \
		moc_hildonwindowplugin.o \
		moc_qdeclarativeprocess.o \
		moc_plugin.o \
		moc_qdeclarativesettings.o
DIST          = /targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/release.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/mobility.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		components.pro
QMAKE_TARGET  = hildonplugin
DESTDIR       = 
TARGET        = libhildonplugin.so
TARGETD       = libhildonplugin.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)



Makefile: components.pro  /targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/linux-g++-maemo5/qmake.conf /targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/default_pre.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/release.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/mobility.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/lex.prf \
		/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDeclarative.prl \
		/usr/lib/libQtScript.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtSvg.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXmlPatterns.prl \
		/usr/lib/libQtNetwork.prl
	$(QMAKE) PREFIX=/usr -o Makefile components.pro
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/common/unix.conf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/common/linux.conf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/qconfig.pri:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt_functions.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt_config.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/default_pre.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/release.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/default_post.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/mobility.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/qt.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/moc.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/unix/thread.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/warn_on.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/resources.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/uic.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/yacc.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/lex.prf:
/targets/FREMANTLE_ARMEL_GCC472/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDeclarative.prl:
/usr/lib/libQtScript.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtSvg.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXmlPatterns.prl:
/usr/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) PREFIX=/usr -o Makefile components.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hildonplugin1.0.0 || $(MKDIR) .tmp/hildonplugin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hildonplugin1.0.0/ && $(COPY_FILE) --parents src/fileinfothread_p.h src/fileproperty_p.h src/qdeclarativefolderlistmodel.h src/filesystemmodel.h src/hildonimageprovider.h src/hildonscreenplugin.h src/hildonsystemplugin.h src/hildonthemeplugin.h src/maskeditem.h src/maskeffect.h src/effects.h src/hildonenums.h src/hildonwindowplugin.h src/qdeclarativeprocess.h src/plugin.h src/qdeclarativesettings.h .tmp/hildonplugin1.0.0/ && $(COPY_FILE) --parents src/fileinfothread.cpp src/qdeclarativefolderlistmodel.cpp src/filesystemmodel.cpp src/hildonscreenplugin.cpp src/hildonsystemplugin.cpp src/maskeditem.cpp src/maskeffect.cpp src/effects.cpp src/hildonwindowplugin.cpp src/qdeclarativeprocess.cpp src/qdeclarativesettings.cpp src/hildonthemeplugin.cpp src/hildonimageprovider.cpp .tmp/hildonplugin1.0.0/ && (cd `dirname .tmp/hildonplugin1.0.0` && $(TAR) hildonplugin1.0.0.tar hildonplugin1.0.0 && $(COMPRESS) hildonplugin1.0.0.tar) && $(MOVE) `dirname .tmp/hildonplugin1.0.0`/hildonplugin1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hildonplugin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_fileinfothread_p.cpp moc_qdeclarativefolderlistmodel.cpp moc_filesystemmodel.cpp moc_hildonscreenplugin.cpp moc_hildonsystemplugin.cpp moc_hildonthemeplugin.cpp moc_maskeditem.cpp moc_maskeffect.cpp moc_effects.cpp moc_hildonenums.cpp moc_hildonwindowplugin.cpp moc_qdeclarativeprocess.cpp moc_plugin.cpp moc_qdeclarativesettings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fileinfothread_p.cpp moc_qdeclarativefolderlistmodel.cpp moc_filesystemmodel.cpp moc_hildonscreenplugin.cpp moc_hildonsystemplugin.cpp moc_hildonthemeplugin.cpp moc_maskeditem.cpp moc_maskeffect.cpp moc_effects.cpp moc_hildonenums.cpp moc_hildonwindowplugin.cpp moc_qdeclarativeprocess.cpp moc_plugin.cpp moc_qdeclarativesettings.cpp
moc_fileinfothread_p.cpp: src/fileproperty_p.h \
		src/fileinfothread_p.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/fileinfothread_p.h -o moc_fileinfothread_p.cpp

moc_qdeclarativefolderlistmodel.cpp: src/fileinfothread_p.h \
		src/fileproperty_p.h \
		src/qdeclarativefolderlistmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/qdeclarativefolderlistmodel.h -o moc_qdeclarativefolderlistmodel.cpp

moc_filesystemmodel.cpp: src/qdeclarativefolderlistmodel.h \
		src/fileinfothread_p.h \
		src/fileproperty_p.h \
		src/filesystemmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/filesystemmodel.h -o moc_filesystemmodel.cpp

moc_hildonscreenplugin.cpp: src/hildonscreenplugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/hildonscreenplugin.h -o moc_hildonscreenplugin.cpp

moc_hildonsystemplugin.cpp: src/hildonenums.h \
		src/hildonsystemplugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/hildonsystemplugin.h -o moc_hildonsystemplugin.cpp

moc_hildonthemeplugin.cpp: src/hildonthemeplugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/hildonthemeplugin.h -o moc_hildonthemeplugin.cpp

moc_maskeditem.cpp: src/maskeffect.h \
		src/maskeditem.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/maskeditem.h -o moc_maskeditem.cpp

moc_maskeffect.cpp: src/maskeffect.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/maskeffect.h -o moc_maskeffect.cpp

moc_effects.cpp: src/effects.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/effects.h -o moc_effects.cpp

moc_hildonenums.cpp: src/hildonenums.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/hildonenums.h -o moc_hildonenums.cpp

moc_hildonwindowplugin.cpp: src/hildonenums.h \
		src/hildonwindowplugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/hildonwindowplugin.h -o moc_hildonwindowplugin.cpp

moc_qdeclarativeprocess.cpp: src/qdeclarativeprocess.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/qdeclarativeprocess.h -o moc_qdeclarativeprocess.cpp

moc_plugin.cpp: src/hildonscreenplugin.h \
		src/hildonwindowplugin.h \
		src/hildonenums.h \
		src/hildonsystemplugin.h \
		src/hildonthemeplugin.h \
		src/hildonimageprovider.h \
		src/filesystemmodel.h \
		src/qdeclarativefolderlistmodel.h \
		src/fileinfothread_p.h \
		src/fileproperty_p.h \
		src/maskeditem.h \
		src/maskeffect.h \
		src/effects.h \
		src/qdeclarativeprocess.h \
		src/qdeclarativesettings.h \
		src/plugin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/plugin.h -o moc_plugin.cpp

moc_qdeclarativesettings.cpp: src/qdeclarativesettings.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/qdeclarativesettings.h -o moc_qdeclarativesettings.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

fileinfothread.o: src/fileinfothread.cpp src/fileinfothread_p.h \
		src/fileproperty_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileinfothread.o src/fileinfothread.cpp

qdeclarativefolderlistmodel.o: src/qdeclarativefolderlistmodel.cpp src/qdeclarativefolderlistmodel.h \
		src/fileinfothread_p.h \
		src/fileproperty_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdeclarativefolderlistmodel.o src/qdeclarativefolderlistmodel.cpp

filesystemmodel.o: src/filesystemmodel.cpp src/filesystemmodel.h \
		src/qdeclarativefolderlistmodel.h \
		src/fileinfothread_p.h \
		src/fileproperty_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filesystemmodel.o src/filesystemmodel.cpp

hildonscreenplugin.o: src/hildonscreenplugin.cpp src/hildonscreenplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hildonscreenplugin.o src/hildonscreenplugin.cpp

hildonsystemplugin.o: src/hildonsystemplugin.cpp src/hildonsystemplugin.h \
		src/hildonenums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hildonsystemplugin.o src/hildonsystemplugin.cpp

maskeditem.o: src/maskeditem.cpp src/maskeditem.h \
		src/maskeffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maskeditem.o src/maskeditem.cpp

maskeffect.o: src/maskeffect.cpp src/maskeffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maskeffect.o src/maskeffect.cpp

effects.o: src/effects.cpp src/effects.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effects.o src/effects.cpp

hildonwindowplugin.o: src/hildonwindowplugin.cpp src/hildonwindowplugin.h \
		src/hildonenums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hildonwindowplugin.o src/hildonwindowplugin.cpp

qdeclarativeprocess.o: src/qdeclarativeprocess.cpp src/qdeclarativeprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdeclarativeprocess.o src/qdeclarativeprocess.cpp

qdeclarativesettings.o: src/qdeclarativesettings.cpp src/qdeclarativesettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdeclarativesettings.o src/qdeclarativesettings.cpp

hildonthemeplugin.o: src/hildonthemeplugin.cpp src/hildonthemeplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hildonthemeplugin.o src/hildonthemeplugin.cpp

hildonimageprovider.o: src/hildonimageprovider.cpp src/hildonimageprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hildonimageprovider.o src/hildonimageprovider.cpp

moc_fileinfothread_p.o: moc_fileinfothread_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fileinfothread_p.o moc_fileinfothread_p.cpp

moc_qdeclarativefolderlistmodel.o: moc_qdeclarativefolderlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdeclarativefolderlistmodel.o moc_qdeclarativefolderlistmodel.cpp

moc_filesystemmodel.o: moc_filesystemmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filesystemmodel.o moc_filesystemmodel.cpp

moc_hildonscreenplugin.o: moc_hildonscreenplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hildonscreenplugin.o moc_hildonscreenplugin.cpp

moc_hildonsystemplugin.o: moc_hildonsystemplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hildonsystemplugin.o moc_hildonsystemplugin.cpp

moc_hildonthemeplugin.o: moc_hildonthemeplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hildonthemeplugin.o moc_hildonthemeplugin.cpp

moc_maskeditem.o: moc_maskeditem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maskeditem.o moc_maskeditem.cpp

moc_maskeffect.o: moc_maskeffect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maskeffect.o moc_maskeffect.cpp

moc_effects.o: moc_effects.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_effects.o moc_effects.cpp

moc_hildonenums.o: moc_hildonenums.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hildonenums.o moc_hildonenums.cpp

moc_hildonwindowplugin.o: moc_hildonwindowplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hildonwindowplugin.o moc_hildonwindowplugin.cpp

moc_qdeclarativeprocess.o: moc_qdeclarativeprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdeclarativeprocess.o moc_qdeclarativeprocess.cpp

moc_plugin.o: moc_plugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plugin.o moc_plugin.cpp

moc_qdeclarativesettings.o: moc_qdeclarativesettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdeclarativesettings.o moc_qdeclarativesettings.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ || $(MKDIR) $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ 
	-$(INSTALL_PROGRAM) "$(TARGET)" "$(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ 


install_qml_files: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ || $(MKDIR) $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ 
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/AbstractMenuItem.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ApplicationWindow.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ApplicationWindowStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/BackButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/BusyIndicator.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Button.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ButtonRow.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ButtonRowStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ButtonStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/cancel.png $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/CheckBox.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/CheckBoxStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Contact.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ContextMenu.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ContextMenuItem.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ContextMenuLayout.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ContextMenuStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/CreateObject.js $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Dialog.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/DialogButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/DialogButtonStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/DialogStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/EditBar.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/EditButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/EditButtonStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/fader.png $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Fader.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/FileBrowserDelegate.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/FileBrowserDialog.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/FilterBox.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/FilterListView.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Flickable.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/InfoBanner.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/InfoNote.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/InputDialog.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/InputDialogStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Label.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/LabelStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/LinkLabel.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ListItem.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ListView.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Menu.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MenuAction.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MenuActionGroup.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MenuItem.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MenuLayout.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MenuLayoutBinding.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MenuStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MinimizeButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MouseArea.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MultiSelectionDialog.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/MultiSelectionItem.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/NewFolderDialog.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Page.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/PageStack.js $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/PageStack.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/PageStackWindow.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/PageStackWindowStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Popup.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/PopupMinimizeButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ProgressBar.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ProgressBarStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/qmldir $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/QueryDialog.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/QueryDialogStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/RangeModel.js $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/RangeModel.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/RatingIndicator.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/RatingIndicatorStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ScrollDecorator.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SearchBox.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SearchTextField.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SelectionButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SelectionButtonStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SelectionDelegate.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SelectionDialog.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SelectionDialogStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SelectionItem.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Slider.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/SliderStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/StatusArea.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/StatusBar.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Style.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/StylusButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/StylusButtonStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TabBar.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TabButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TabButtonStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TabGroup.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TableColumn.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TableView.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TextArea.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TextAreaStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TextField.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TextFieldStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/TitleArea.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ToolBar.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ToolBarLayout.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ToolBarStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ToolButton.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/ToolButtonStyle.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/Utils.js $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/
	-$(INSTALL_FILE) /home/qwazix/scratchboxenv/mozembed/qtcomptest/components/qml/WebShortcut.qml $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/


uninstall_qml_files:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/AbstractMenuItem.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ApplicationWindow.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ApplicationWindowStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/BackButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/BusyIndicator.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Button.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ButtonRow.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ButtonRowStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ButtonStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/cancel.png 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/CheckBox.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/CheckBoxStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Contact.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ContextMenu.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ContextMenuItem.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ContextMenuLayout.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ContextMenuStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/CreateObject.js 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Dialog.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/DialogButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/DialogButtonStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/DialogStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/EditBar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/EditButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/EditButtonStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/fader.png 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Fader.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/FileBrowserDelegate.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/FileBrowserDialog.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/FilterBox.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/FilterListView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Flickable.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/InfoBanner.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/InfoNote.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/InputDialog.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/InputDialogStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Label.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/LabelStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/LinkLabel.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ListItem.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ListView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Menu.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MenuAction.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MenuActionGroup.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MenuItem.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MenuLayout.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MenuLayoutBinding.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MenuStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MinimizeButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MouseArea.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MultiSelectionDialog.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/MultiSelectionItem.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/NewFolderDialog.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Page.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/PageStack.js 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/PageStack.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/PageStackWindow.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/PageStackWindowStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Popup.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/PopupMinimizeButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ProgressBar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ProgressBarStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/qmldir 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/QueryDialog.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/QueryDialogStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/RangeModel.js 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/RangeModel.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/RatingIndicator.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/RatingIndicatorStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ScrollDecorator.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SearchBox.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SearchTextField.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SelectionButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SelectionButtonStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SelectionDelegate.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SelectionDialog.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SelectionDialogStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SelectionItem.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Slider.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/SliderStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/StatusArea.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/StatusBar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Style.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/StylusButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/StylusButtonStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TabBar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TabButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TabButtonStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TabGroup.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TableColumn.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TableView.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TextArea.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TextAreaStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TextField.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TextFieldStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/TitleArea.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ToolBar.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ToolBarLayout.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ToolBarStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ToolButton.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ToolButtonStyle.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/Utils.js 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/WebShortcut.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/lib/qt4/imports/org/hildon/components/ 


install:  install_target install_qml_files  FORCE

uninstall: uninstall_target uninstall_qml_files   FORCE

FORCE:

